export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const FETCH_DATA = "FETCH_DATA";
export const DATA_FETCH_ERROR = "DATA_FETCH_ERROR";
